# Generated by Django 5.2.1 on 2025-06-27 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0004_gamescorelesson_lessonfinished_delete_gamescore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessonfinished',
            old_name='lesson_id',
            new_name='lesson',
        ),
        migrations.RenameField(
            model_name='lessonfinished',
            old_name='user_id',
            new_name='user',
        ),
    ]
