# Generated by Django 5.2.1 on 2025-07-02 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0005_rename_lesson_id_lessonfinished_lesson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='level',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
