services:
  web:
    build: 
      context: ./backend
    container_name: django_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app_backend
    working_dir: /app_backend
    ports:
      - "8000:8000"

  frontend: 
    build:
      context: ./frontend
    container_name: react_frontend
    command: npm run dev
    volumes:
      - ./frontend:/app
    working_dir: /app
    ports:
      - "5173:5173"


